apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-service
  name: redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    tier: db
  type: ClusterIP
